services:
  app:
    container_name: lx-games-cartridge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_EXTERNAL}:${APP_PORT}"
    volumes:
      - ./runtime:/app/runtime
